name: Do a Duolingo lesson

on:
  workflow_dispatch:
    inputs:
      lessons:
        default: 1
        description: 'Number of lessons to be completed'
        required: false
        type: number
      date:
        default: '2024-10-10'
        description: 'Lesson date'
        required: false
        type: string

jobs:
  study:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: node index.js
        env:
          DUOLINGO_JWT: ${{ secrets.DUOLINGO_JWT }}
          LESSONS: ${{ inputs.lessons }}
          LESSON_DATE: ${{ inputs.date }}
